export const CROCKPOT_RECIPES = [
  {
    id: 'cp-cabbage-sausage',
    title: 'Slow cooker cabbage and sausage',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'sausage'],
    ingredients: ['Smoked sausage', 'Cabbage', 'Onion', 'Potatoes'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-cabbage-and-sausage/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'Cabbage and sausage (plate)', calories: 420, protein_g: 20, carbs_g: 28, fat_g: 22, fiber_g: 6, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-lentil-chili',
    title: 'Slow cooker vegetarian lentil chili',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chili', 'lentil', 'veg'],
    ingredients: ['Lentils', 'Beans', 'Tomatoes', 'Chili seasoning'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-vegetarian-lentil-chili/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'Lentil chili (bowl)', calories: 340, protein_g: 18, carbs_g: 48, fat_g: 6, fiber_g: 16, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-beef-ragu',
    title: 'Sunday slow cooker beef ragu',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'pasta'],
    ingredients: ['Beef', 'Tomatoes', 'Carrots', 'Onion', 'Pasta'],
    recipeUrl: 'https://www.budgetbytes.com/sunday-slow-cooker-beef-ragu/',
    recipeSource: 'Budget Bytes',
    logNames: ['Pasta with sauce (2 cups)', 'Lean ground beef (4 oz)'],
  },
  {
    id: 'cp-white-bean-soup',
    title: 'Slow cooker white bean soup',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'soup', 'bean', 'veg'],
    ingredients: ['Beans', 'Carrots', 'Onion', 'Broth'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-white-bean-soup/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'White bean soup (bowl)', calories: 310, protein_g: 16, carbs_g: 44, fat_g: 6, fiber_g: 12, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-chicken-tortilla-soup',
    title: 'Slow cooker chicken tortilla soup',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'soup', 'taco'],
    ingredients: ['Chicken', 'Tomatoes', 'Beans', 'Corn', 'Tortilla chips'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-chicken-tortilla-soup/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'Chicken tortilla soup (bowl)', calories: 380, protein_g: 28, carbs_g: 36, fat_g: 12, fiber_g: 8, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-five-spice-chicken',
    title: 'Slow cooker five-spice chicken',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken'],
    ingredients: ['Chicken', 'Soy sauce', 'Garlic', 'Rice'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-5-spice-chicken/',
    recipeSource: 'Budget Bytes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'cp-italian-chicken-peppers',
    title: 'Slow cooker Italian chicken and peppers',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'pepper'],
    ingredients: ['Chicken', 'Bell peppers', 'Onion', 'Tomatoes'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-italian-chicken-and-peppers/',
    recipeSource: 'Budget Bytes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'cp-black-bean-soup',
    title: 'Slow cooker black bean soup',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'soup', 'bean', 'veg'],
    ingredients: ['Beans', 'Onion', 'Garlic', 'Broth'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-black-bean-soup/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'Black bean soup (bowl)', calories: 300, protein_g: 15, carbs_g: 46, fat_g: 5, fiber_g: 14, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-steel-cut-oatmeal',
    title: 'Slow cooker steel-cut oatmeal',
    meal: 'breakfast',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot'],
    ingredients: ['Rolled oats', 'Milk', 'Cinnamon'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-steel-cut-oatmeal/',
    recipeSource: 'Budget Bytes',
    logNames: ['Oatmeal (1 cup cooked)', 'Milk (1 cup)'],
  },
  {
    id: 'cp-chicken-tikka',
    title: 'Slow cooker chicken tikka masala',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'curry'],
    ingredients: ['Chicken', 'Tomato sauce', 'Cream', 'Rice'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-chicken-tikka-masala/',
    recipeSource: 'Budget Bytes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'cp-sesame-beef',
    title: 'Slow cooker sesame beef',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef'],
    ingredients: ['Beef', 'Soy sauce', 'Sesame', 'Rice', 'Broccoli'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-sesame-beef/',
    recipeSource: 'Budget Bytes',
    logNames: ['Lean ground beef (4 oz)', 'White rice (1 cup)', 'Broccoli (1 cup)'],
  },
  {
    id: 'cp-chicken-noodle-soup',
    title: 'Slow cooker chicken noodle soup',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'soup', 'pasta'],
    ingredients: ['Chicken', 'Egg noodles', 'Carrots', 'Celery', 'Broth'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-chicken-noodle-soup/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'Chicken noodle soup (bowl)', calories: 360, protein_g: 26, carbs_g: 38, fat_g: 8, fiber_g: 4, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-white-chicken-chili',
    title: 'Slow cooker white chicken chili',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'chili', 'bean'],
    ingredients: ['Chicken', 'Beans', 'Salsa verde', 'Broth'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-white-chicken-chili/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'White chicken chili (bowl)', calories: 390, protein_g: 32, carbs_g: 28, fat_g: 12, fiber_g: 8, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-coconut-curry-lentils',
    title: 'Slow cooker coconut curry lentils',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'lentil', 'curry', 'veg'],
    ingredients: ['Lentils', 'Coconut milk', 'Curry paste', 'Rice'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-coconut-curry-lentils/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'Coconut curry lentils (bowl)', calories: 420, protein_g: 18, carbs_g: 52, fat_g: 14, fiber_g: 14, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-giant-meatballs',
    title: 'Giant slow cooker meatballs',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'pasta'],
    ingredients: ['Ground beef', 'Marinara', 'Pasta'],
    recipeUrl: 'https://www.budgetbytes.com/giant-slow-cooker-meatballs/',
    recipeSource: 'Budget Bytes',
    logNames: ['Pasta with sauce (2 cups)', 'Lean ground beef (4 oz)'],
  },
  {
    id: 'cp-slow-cooker-chicken',
    title: 'Slow cooker shredded chicken',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken'],
    ingredients: ['Chicken', 'Broth', 'Onion'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-chicken/',
    recipeSource: 'Budget Bytes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'cp-jerk-chicken',
    title: 'Slow cooker jerk chicken',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken'],
    ingredients: ['Chicken', 'Onion', 'Rice'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-jerk-chicken/',
    recipeSource: 'Budget Bytes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'cp-pineapple-teriyaki-chicken',
    title: 'Slow cooker pineapple teriyaki chicken',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken'],
    ingredients: ['Chicken', 'Pineapple', 'Teriyaki sauce', 'Rice'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-pineapple-teriyaki-chicken/',
    recipeSource: 'Budget Bytes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'cp-jambalaya',
    title: 'Slow cooker jambalaya',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'sausage', 'rice'],
    ingredients: ['Chicken', 'Smoked sausage', 'Rice', 'Tomatoes', 'Bell peppers'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-jambalaya/',
    recipeSource: 'Budget Bytes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'cp-potato-soup',
    title: 'Slow cooker potato soup',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'soup', 'potato'],
    ingredients: ['Potatoes', 'Onion', 'Broth', 'Cream'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-potato-soup/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'Potato soup (bowl)', calories: 360, protein_g: 10, carbs_g: 42, fat_g: 16, fiber_g: 4, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-chicken-ropa-vieja',
    title: 'Slow cooker chicken ropa vieja',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'pepper'],
    ingredients: ['Chicken', 'Bell peppers', 'Onion', 'Tomatoes', 'Rice'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-chicken-ropa-vieja/',
    recipeSource: 'Budget Bytes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'cp-beef-stew',
    title: 'Crockpot beef stew',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'stew', 'potato'],
    ingredients: ['Beef', 'Potatoes', 'Carrots', 'Celery', 'Broth'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-beef-stew/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'Beef stew (bowl)', calories: 420, protein_g: 28, carbs_g: 32, fat_g: 16, fiber_g: 5, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-salsa-chicken',
    title: 'Crock pot salsa chicken',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'taco'],
    ingredients: ['Chicken', 'Salsa', 'Chili seasoning'],
    recipeUrl: 'https://www.budgetbytes.com/crock-pot-salsa-chicken/',
    recipeSource: 'Budget Bytes',
    logNames: ['Tacos (2)'],
  },
  {
    id: 'cp-buffalo-chicken',
    title: 'Slow cooker buffalo chicken',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken'],
    ingredients: ['Chicken', 'Hot sauce', 'Butter', 'Buns'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-buffalo-chicken/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'Buffalo chicken sandwich', calories: 480, protein_g: 34, carbs_g: 36, fat_g: 18, fiber_g: 2, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-bbq-chicken',
    title: 'Slow cooker BBQ chicken',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'bbq'],
    ingredients: ['Chicken', 'BBQ sauce', 'Buns'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-bbq-chicken/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'BBQ chicken sandwich', calories: 490, protein_g: 34, carbs_g: 42, fat_g: 16, fiber_g: 2, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-chicken-tetrazzini',
    title: 'Crockpot chicken tetrazzini',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'pasta'],
    ingredients: ['Chicken', 'Pasta', 'Mushrooms', 'Cream cheese'],
    recipeUrl: 'https://www.budgetbytes.com/crockpot-chicken-tetrazzini/',
    recipeSource: 'Budget Bytes',
    logNames: ['Pasta with sauce (2 cups)', 'Chicken breast (4 oz)'],
  },
  {
    id: 'cp-chicken-ramen',
    title: 'Slow cooker chicken and vegetable ramen',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'soup'],
    ingredients: ['Chicken', 'Ramen', 'Frozen vegetables', 'Broth'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-chicken-and-vegetables-ramen/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'Chicken ramen (bowl)', calories: 440, protein_g: 28, carbs_g: 48, fat_g: 12, fiber_g: 4, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-mississippi-chicken',
    title: 'Mississippi chicken',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken'],
    ingredients: ['Chicken breast', 'Butter', 'Pepperoncini'],
    recipeUrl: 'https://www.budgetbytes.com/mississippi-chicken/',
    recipeSource: 'Budget Bytes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'cp-mississippi-pot-roast',
    title: 'Mississippi pot roast',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef'],
    ingredients: ['Beef', 'Butter', 'Pepperoncini'],
    recipeUrl: 'https://www.budgetbytes.com/mississippi-pot-roast/',
    recipeSource: 'Budget Bytes',
    logItems: [
      { name: 'Pot roast (plate)', calories: 480, protein_g: 36, carbs_g: 12, fat_g: 28, fiber_g: 1, meal: 'dinner' },
    ],
  },
  {
    id: 'cp-taco-chicken-bowls',
    title: 'Slow cooker chicken taco bowls',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'taco', 'bean'],
    ingredients: ['Chicken', 'Salsa', 'Black beans', 'Corn', 'Rice'],
    recipeUrl: 'https://www.budgetbytes.com/taco-chicken-bowls/',
    recipeSource: 'Budget Bytes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'cp-shredded-chicken',
    title: 'Crockpot pulled chicken',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken'],
    ingredients: ['Chicken breast', 'Broth'],
    recipeUrl: 'https://www.budgetbytes.com/shredded-chicken/',
    recipeSource: 'Budget Bytes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'cp-marinara',
    title: 'Slow cooker marinara',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'pasta', 'veg'],
    ingredients: ['Tomatoes', 'Onion', 'Garlic', 'Pasta'],
    recipeUrl: 'https://www.budgetbytes.com/slow-cooker-marinara/',
    recipeSource: 'Budget Bytes',
    logNames: ['Pasta with sauce (2 cups)'],
  },
  {
    id: 'cp-green-beans',
    title: 'Southern slow cooker green beans',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot'],
    ingredients: ['Green beans', 'Bacon', 'Onion'],
    recipeUrl: 'https://www.budgetbytes.com/southern-slow-cooker-green-beans/',
    recipeSource: 'Budget Bytes',
    logNames: ['Broccoli (1 cup)'],
    logItems: [
      { name: 'Green beans with bacon', calories: 160, protein_g: 8, carbs_g: 12, fat_g: 8, fiber_g: 4, meal: 'dinner' },
    ],
  },
  {
    id: 'st-pork-green-chile',
    title: 'Slow cooker pork and green chile stew',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'pork', 'stew', 'chili'],
    ingredients: ['Pork', 'Green chiles', 'Potatoes', 'Onion'],
    recipeUrl: 'https://www.skinnytaste.com/slow-cooker-pork-and-green-chile-stew/',
    recipeSource: 'Skinnytaste',
    logItems: [
      { name: 'Pork green chile stew (bowl)', calories: 390, protein_g: 28, carbs_g: 24, fat_g: 16, fiber_g: 4, meal: 'dinner' },
    ],
  },
  {
    id: 'st-sazon-pork-chops',
    title: 'Crock pot sazon pork chops with peppers',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'pork', 'pepper'],
    ingredients: ['Pork chops', 'Bell peppers', 'Onion'],
    recipeUrl: 'https://www.skinnytaste.com/crock-pot-sazon-pork-chops-with-peppers/',
    recipeSource: 'Skinnytaste',
    logItems: [
      { name: 'Sazon pork chops (plate)', calories: 410, protein_g: 32, carbs_g: 14, fat_g: 22, fiber_g: 3, meal: 'dinner' },
    ],
  },
  {
    id: 'st-italian-beef-hoagies',
    title: 'Slow cooker Italian beef hoagies',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'sandwich'],
    ingredients: ['Beef', 'Hoagie rolls', 'Bell peppers'],
    recipeUrl: 'https://www.skinnytaste.com/slow-cooker-italian-beef-hoagies-our-first-meal-in-our-new-home/',
    recipeSource: 'Skinnytaste',
    logItems: [
      { name: 'Italian beef hoagie', calories: 540, protein_g: 34, carbs_g: 44, fat_g: 22, fiber_g: 3, meal: 'dinner' },
    ],
  },
  {
    id: 'st-chipotle-chicken-zucchini',
    title: 'Slow cooker chipotle chicken zucchini',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'soup'],
    ingredients: ['Chicken', 'Zucchini', 'Chipotle', 'Broth'],
    recipeUrl: 'https://www.skinnytaste.com/slow-cooker-chipotle-chicken-zucchini/',
    recipeSource: 'Skinnytaste',
    logItems: [
      { name: 'Chipotle chicken zucchini soup', calories: 320, protein_g: 28, carbs_g: 16, fat_g: 12, fiber_g: 4, meal: 'dinner' },
    ],
  },
  {
    id: 'st-french-dip',
    title: 'Slow cooker French dip sandwiches',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'sandwich'],
    ingredients: ['Beef', 'Buns', 'Broth'],
    recipeUrl: 'https://www.skinnytaste.com/slow-cooker-french-dip-sandwiches-with/',
    recipeSource: 'Skinnytaste',
    logItems: [
      { name: 'French dip sandwich', calories: 520, protein_g: 34, carbs_g: 40, fat_g: 20, fiber_g: 2, meal: 'dinner' },
    ],
  },
  {
    id: 'st-chicken-black-bean-tacos',
    title: 'Slow cooker chicken black bean tacos',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'taco', 'bean'],
    ingredients: ['Chicken', 'Black beans', 'Tortillas', 'Salsa'],
    recipeUrl: 'https://www.skinnytaste.com/slow-cooker-chicken-black-bean-tacos/',
    recipeSource: 'Skinnytaste',
    logNames: ['Tacos (2)'],
  },
  {
    id: 'st-moroccan-chickpea',
    title: 'Slow cooker Moroccan chickpea stew',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'soup', 'bean', 'veg'],
    ingredients: ['Chickpeas', 'Tomatoes', 'Onion', 'Spices'],
    recipeUrl: 'https://www.skinnytaste.com/slow-cooker-moroccan-chickpea-and/',
    recipeSource: 'Skinnytaste',
    logItems: [
      { name: 'Moroccan chickpea stew (bowl)', calories: 340, protein_g: 14, carbs_g: 52, fat_g: 8, fiber_g: 12, meal: 'dinner' },
    ],
  },
  {
    id: 'st-turkey-chili',
    title: 'Crock pot kid-friendly turkey chili',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'turkey', 'chili', 'bean'],
    ingredients: ['Ground turkey', 'Beans', 'Tomatoes', 'Chili seasoning'],
    recipeUrl: 'https://www.skinnytaste.com/crock-pot-kid-friendly-turkey-chili/',
    recipeSource: 'Skinnytaste',
    logItems: [
      { name: 'Turkey chili (bowl)', calories: 360, protein_g: 28, carbs_g: 32, fat_g: 10, fiber_g: 10, meal: 'dinner' },
    ],
  },
  {
    id: 'st-beef-meatballs-rabe',
    title: 'Slow cooker beef meatballs with broccoli rabe',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef'],
    ingredients: ['Meatballs', 'Greens', 'Garlic'],
    recipeUrl: 'https://www.skinnytaste.com/slow-cooker-beef-meatballs-with-broccoli-rabe/',
    recipeSource: 'Skinnytaste',
    logItems: [
      { name: 'Meatballs with greens (plate)', calories: 430, protein_g: 28, carbs_g: 16, fat_g: 24, fiber_g: 4, meal: 'dinner' },
    ],
  },
  {
    id: 'st-chicken-enchilada-sp',
    title: 'Slow cooker chicken enchilada sweet potatoes',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken'],
    ingredients: ['Chicken', 'Sweet potatoes', 'Enchilada sauce'],
    recipeUrl: 'https://www.skinnytaste.com/slow-cooker-chicken-enchilada-sweet-potatoes/',
    recipeSource: 'Skinnytaste',
    logNames: ['Chicken breast (4 oz)', 'Sweet potato (medium)'],
  },
  {
    id: 'st-jalapeno-popper-chili',
    title: 'Slow cooker jalapeño popper chicken chili',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'chili'],
    ingredients: ['Chicken', 'Beans', 'Cream cheese', 'Green chiles'],
    recipeUrl: 'https://www.skinnytaste.com/slow-cooker-paleo-jalapeno-popper/',
    recipeSource: 'Skinnytaste',
    logItems: [
      { name: 'Jalapeño popper chili (bowl)', calories: 410, protein_g: 32, carbs_g: 22, fat_g: 18, fiber_g: 6, meal: 'dinner' },
    ],
  },
  {
    id: 'st-tomatillo-drumsticks',
    title: 'Braised chicken drumsticks in tomatillo sauce',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken'],
    ingredients: ['Chicken', 'Salsa verde', 'Onion'],
    recipeUrl: 'https://www.skinnytaste.com/easy-braised-chicken-drumsticks-in-tomatillo-sauce-instant-pot-slow-cooker-or-stove-top/',
    recipeSource: 'Skinnytaste',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'st-cubed-steak',
    title: 'Braised cubed steak with peppers and olives',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'pepper'],
    ingredients: ['Beef', 'Bell peppers', 'Olives', 'Onion'],
    recipeUrl: 'https://www.skinnytaste.com/braised-cubed-steak-with-peppers-onions-and-olives-instant-pot-and-slow-cooker/',
    recipeSource: 'Skinnytaste',
    logItems: [
      { name: 'Cubed steak with peppers', calories: 430, protein_g: 32, carbs_g: 14, fat_g: 22, fiber_g: 3, meal: 'dinner' },
    ],
  },
  {
    id: 'st-chicken-taco-chili',
    title: 'Crock pot chicken taco chili',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'chili', 'taco', 'bean'],
    ingredients: ['Chicken', 'Beans', 'Corn', 'Tomatoes', 'Taco seasoning'],
    recipeUrl: 'https://www.skinnytaste.com/crock-pot-chicken-taco-chili-4-pts/',
    recipeSource: 'Skinnytaste',
    logItems: [
      { name: 'Chicken taco chili (bowl)', calories: 380, protein_g: 30, carbs_g: 36, fat_g: 10, fiber_g: 10, meal: 'dinner' },
    ],
  },
  {
    id: 'st-slow-cooker-chili',
    title: 'Slow cooker beef chili',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'chili', 'bean'],
    ingredients: ['Ground beef', 'Beans', 'Tomatoes', 'Chili seasoning'],
    recipeUrl: 'https://www.skinnytaste.com/slow-cooker-chili/',
    recipeSource: 'Skinnytaste',
    logItems: [
      { name: 'Beef chili (bowl)', calories: 400, protein_g: 28, carbs_g: 32, fat_g: 16, fiber_g: 10, meal: 'dinner' },
    ],
  },
  {
    id: 'st-birria-tacos',
    title: 'Slow cooker birria tacos',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'taco'],
    ingredients: ['Beef', 'Tomatoes', 'Corn tortillas', 'Onion'],
    recipeUrl: 'https://www.skinnytaste.com/slow-cooker-birria-tacos-recipe/',
    recipeSource: 'Skinnytaste',
    logNames: ['Tacos (2)'],
  },
  {
    id: 'st-beef-tacos',
    title: 'Slow cooker beef tacos',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'taco'],
    ingredients: ['Ground beef', 'Taco shells', 'Tomato sauce', 'Onion'],
    recipeUrl: 'https://www.skinnytaste.com/madisons-favorite-slow-cooker-beef-tacos/',
    recipeSource: 'Skinnytaste',
    logNames: ['Tacos (2)'],
  },
  {
    id: 'st-sweet-potatoes',
    title: 'Slow cooker sweet potatoes',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot'],
    ingredients: ['Sweet potatoes'],
    recipeUrl: 'https://www.skinnytaste.com/easiest-slow-cooker-sweet-potatoes/',
    recipeSource: 'Skinnytaste',
    logNames: ['Sweet potato (medium)'],
  },
  {
    id: 'sr-chicken-chili',
    title: 'Slow cooker shredded chicken chili',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'chili', 'bean'],
    ingredients: ['Chicken thighs', 'Beans', 'Tomatoes', 'Corn', 'Broth'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/slow_cooker_shredded_chicken_chili/',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Chicken chili (bowl)', calories: 390, protein_g: 32, carbs_g: 34, fat_g: 10, fiber_g: 10, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-pot-roast',
    title: 'Slow cooker pot roast',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'potato'],
    ingredients: ['Beef', 'Potatoes', 'Carrots', 'Onion', 'Broth'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/slow_cooker_pot_roast/',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Pot roast with vegetables', calories: 470, protein_g: 36, carbs_g: 28, fat_g: 20, fiber_g: 4, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-bbq-chicken',
    title: 'Slow cooker barbecue chicken',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'bbq'],
    ingredients: ['Chicken thighs', 'BBQ sauce'],
    recipeUrl: 'https://www.simplyrecipes.com/slow-cooker-barbecue-chicken-recipe-11888749',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Barbecue chicken (plate)', calories: 430, protein_g: 34, carbs_g: 24, fat_g: 16, fiber_g: 1, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-brisket',
    title: 'Slow cooker brisket',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'bbq'],
    ingredients: ['Beef', 'BBQ sauce', 'Onion'],
    recipeUrl: 'https://www.simplyrecipes.com/slow-cooker-brisket-recipe-11837224',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Brisket (plate)', calories: 480, protein_g: 36, carbs_g: 16, fat_g: 26, fiber_g: 1, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-chicken-tacos',
    title: 'Slow cooker chicken tacos',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'taco'],
    ingredients: ['Chicken', 'Salsa', 'Tortillas'],
    recipeUrl: 'https://www.simplyrecipes.com/slow-cooker-chicken-tacos-recipe-11819415',
    recipeSource: 'Simply Recipes',
    logNames: ['Tacos (2)'],
  },
  {
    id: 'sr-beef-bean-chili',
    title: 'Slow cooker beef and bean chili',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'chili', 'bean'],
    ingredients: ['Ground beef', 'Beans', 'Tomatoes', 'Green chiles'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/slow_cooker_beef_and_bean_chili/',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Beef and bean chili (bowl)', calories: 410, protein_g: 28, carbs_g: 34, fat_g: 16, fiber_g: 10, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-beef-stew',
    title: 'Slow cooker beef stew',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'stew', 'potato'],
    ingredients: ['Beef', 'Potatoes', 'Carrots', 'Celery', 'Broth'],
    recipeUrl: 'https://www.simplyrecipes.com/slow-cooker-beef-stew-recipe-6541415',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Beef stew (bowl)', calories: 430, protein_g: 30, carbs_g: 32, fat_g: 16, fiber_g: 5, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-taco-soup',
    title: 'Slow cooker taco soup',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'soup', 'taco'],
    ingredients: ['Ground beef', 'Beans', 'Corn', 'Tomatoes', 'Broth'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/slow_cooker_taco_soup/',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Taco soup (bowl)', calories: 380, protein_g: 24, carbs_g: 36, fat_g: 14, fiber_g: 8, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-buffalo-chicken-chili',
    title: 'Buffalo chicken chili',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'chili'],
    ingredients: ['Chicken', 'Beans', 'Hot sauce', 'Tomatoes'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/buffalo_chicken_chili/',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Buffalo chicken chili (bowl)', calories: 400, protein_g: 32, carbs_g: 28, fat_g: 14, fiber_g: 8, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-sausage-kale-soup',
    title: 'Slow cooker sausage, kale, and potato soup',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'sausage', 'soup', 'potato'],
    ingredients: ['Italian sausage', 'Greens', 'Potatoes', 'Broth'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/slow_cooker_sausage_kale_and_potato_soup/',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Sausage kale potato soup', calories: 390, protein_g: 20, carbs_g: 28, fat_g: 20, fiber_g: 4, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-moroccan-chicken',
    title: 'Slow cooker Moroccan chicken',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken'],
    ingredients: ['Chicken', 'Chickpeas', 'Onion', 'Spices', 'Rice'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/slow_cooker_moroccan_chicken/',
    recipeSource: 'Simply Recipes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'sr-beef-stroganoff',
    title: 'Slow cooker beef stroganoff',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'pasta'],
    ingredients: ['Beef', 'Mushrooms', 'Cream', 'Egg noodles'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/slow_cooker_beef_stroganoff/',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Beef stroganoff (plate)', calories: 520, protein_g: 30, carbs_g: 42, fat_g: 22, fiber_g: 3, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-shredded-chicken',
    title: 'Slow cooker shredded chicken',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken'],
    ingredients: ['Chicken', 'Broth'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/slow_cooker_shredded_chicken/',
    recipeSource: 'Simply Recipes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
  {
    id: 'sr-pulled-pork',
    title: 'Slow cooker pulled pork',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'pork', 'bbq'],
    ingredients: ['Pork shoulder', 'BBQ sauce', 'Buns'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/slow_cooker_pulled_pork/',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Pulled pork sandwich', calories: 530, protein_g: 32, carbs_g: 42, fat_g: 22, fiber_g: 2, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-split-pea',
    title: 'Slow cooker split pea soup',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'soup', 'veg'],
    ingredients: ['Lentils', 'Carrots', 'Onion', 'Broth'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/slow_cooker_split_pea_soup/',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Split pea soup (bowl)', calories: 330, protein_g: 18, carbs_g: 48, fat_g: 6, fiber_g: 14, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-chicken-dumplings',
    title: 'Slow cooker chicken and dumplings',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'soup'],
    ingredients: ['Chicken', 'Biscuits', 'Carrots', 'Peas'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/slow_cooker_chicken_and_dumplings/',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Chicken and dumplings (bowl)', calories: 470, protein_g: 30, carbs_g: 44, fat_g: 16, fiber_g: 4, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-white-chicken-chili',
    title: 'Slow cooker white chicken chili',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken', 'chili', 'bean'],
    ingredients: ['Chicken', 'Beans', 'Green chiles', 'Broth'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/slow_cooker_white_chicken_chili/',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'White chicken chili (bowl)', calories: 380, protein_g: 32, carbs_g: 28, fat_g: 12, fiber_g: 8, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-sloppy-joes',
    title: 'Slow cooker sloppy joes',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'beef', 'sandwich'],
    ingredients: ['Ground beef', 'Tomato sauce', 'Buns', 'Onion'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/easy_slow_cooker_sloppy_joes/',
    recipeSource: 'Simply Recipes',
    logItems: [
      { name: 'Sloppy joe', calories: 480, protein_g: 26, carbs_g: 44, fat_g: 18, fiber_g: 3, meal: 'dinner' },
    ],
  },
  {
    id: 'sr-honey-garlic-chicken',
    title: 'Slow cooker honey garlic chicken',
    meal: 'dinner',
    kidOk: true,
    tags: ['easy', 'kid', 'crockpot', 'chicken'],
    ingredients: ['Chicken', 'Honey', 'Soy sauce', 'Garlic', 'Rice'],
    recipeUrl: 'https://www.simplyrecipes.com/recipes/slow_cooker_honey_garlic_chicken/',
    recipeSource: 'Simply Recipes',
    logNames: ['Chicken breast (4 oz)', 'White rice (1 cup)'],
  },
];
