/** One plate each. Built for a cut: under 450 kcal, about 30g protein or more. */
export const LEAN_RECIPES = [
  {
    id: 'lean-yogurt-eggs',
    title: 'Yogurt, eggs, and berries',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'yogurt', 'egg'],
    ingredients: ['Greek yogurt', 'Eggs', 'Berries'],
    notes: 'Plain yogurt. Berries on the side.',
    logItems: [
      { name: 'Greek yogurt (1 cup)', calories: 130, protein_g: 22, carbs_g: 8, fat_g: 0, fiber_g: 0 },
      { name: 'Eggs (2 large)', calories: 140, protein_g: 12, carbs_g: 1, fat_g: 10, fiber_g: 0 },
      { name: 'Berries (1 cup)', calories: 70, protein_g: 1, carbs_g: 17, fat_g: 0, fiber_g: 8 },
    ],
  },
  {
    id: 'lean-chicken-scramble',
    title: 'Chicken and egg scramble',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken', 'egg'],
    ingredients: ['Chicken breast', 'Eggs', 'Broccoli'],
    notes: 'Chop leftover chicken into the eggs. Broccoli on the side.',
    logItems: [
      { name: 'Chicken breast (4 oz)', calories: 185, protein_g: 35, carbs_g: 0, fat_g: 4, fiber_g: 0 },
      { name: 'Eggs (2 large)', calories: 140, protein_g: 12, carbs_g: 1, fat_g: 10, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
    ],
  },
  {
    id: 'lean-shake-yogurt',
    title: 'Shake and yogurt',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'yogurt'],
    ingredients: ['Protein shake', 'Greek yogurt'],
    notes: 'Drink the shake. Eat the yogurt. No granola.',
    logItems: [
      { name: 'Protein shake', calories: 150, protein_g: 25, carbs_g: 6, fat_g: 2, fiber_g: 1 },
      { name: 'Greek yogurt (1 cup)', calories: 130, protein_g: 22, carbs_g: 8, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-chicken-salad',
    title: 'Chicken salad plate',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Salad', 'Vinaigrette'],
    notes: 'No bread. Use a light vinaigrette.',
    logItems: [
      { name: 'Chicken breast (4 oz)', calories: 185, protein_g: 35, carbs_g: 0, fat_g: 4, fiber_g: 0 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-tuna-plate',
    title: 'Tuna and salad',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Tuna in water', 'Salad', 'Greek yogurt'],
    notes: 'Stir the tuna with yogurt instead of mayo.',
    logItems: [
      { name: 'Tuna in water (4 oz)', calories: 120, protein_g: 26, carbs_g: 0, fat_g: 1, fiber_g: 0 },
      { name: 'Greek yogurt (1 cup)', calories: 130, protein_g: 22, carbs_g: 8, fat_g: 0, fiber_g: 0 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-shrimp-broccoli',
    title: 'Shrimp and broccoli',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'shrimp'],
    ingredients: ['Shrimp', 'Broccoli', 'Lemon'],
    notes: 'Sear the shrimp. Steam the broccoli. Lemon and salt.',
    logItems: [
      { name: 'Shrimp (8 oz)', calories: 240, protein_g: 46, carbs_g: 2, fat_g: 4, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
    ],
  },
  {
    id: 'lean-turkey-rolls',
    title: 'Turkey roll-ups',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'turkey'],
    ingredients: ['Turkey slices', 'Cheese', 'Salad'],
    notes: 'Roll turkey around a cheese stick. Salad on the side.',
    logItems: [
      { name: 'Turkey slices (4 oz)', calories: 140, protein_g: 24, carbs_g: 2, fat_g: 3, fiber_g: 0 },
      { name: 'Cheese stick', calories: 80, protein_g: 7, carbs_g: 1, fat_g: 6, fiber_g: 0 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-chicken-broccoli',
    title: 'Chicken and broccoli',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Broccoli'],
    notes: 'Bake or pan-cook the chicken. No rice.',
    logItems: [
      { name: 'Chicken breast (6 oz)', calories: 280, protein_g: 52, carbs_g: 0, fat_g: 6, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
    ],
  },
  {
    id: 'lean-salmon-plate',
    title: 'Salmon and broccoli',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Salmon', 'Broccoli', 'Greek yogurt'],
    notes: 'Bake the salmon. Yogurt and lemon on the side.',
    logItems: [
      { name: 'Salmon (4 oz)', calories: 230, protein_g: 25, carbs_g: 0, fat_g: 14, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-beef-greens',
    title: 'Lean beef and greens',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'beef'],
    ingredients: ['Lean ground beef', 'Broccoli', 'Greek yogurt'],
    notes: 'Brown the beef with salt and pepper. Skip the bun.',
    logItems: [
      { name: 'Lean ground beef (4 oz)', calories: 220, protein_g: 22, carbs_g: 0, fat_g: 14, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-cod-plate',
    title: 'Cod and greens',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Cod', 'Salad', 'Broccoli'],
    notes: 'Bake the cod with lemon. Greens on the side.',
    logItems: [
      { name: 'Cod (6 oz)', calories: 180, protein_g: 39, carbs_g: 0, fat_g: 2, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-rotisserie',
    title: 'Rotisserie chicken plate',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Rotisserie chicken', 'Broccoli', 'Salad'],
    notes: 'Take the breast. Skip the skin and the potatoes.',
    logItems: [
      { name: 'Rotisserie chicken (5 oz)', calories: 240, protein_g: 35, carbs_g: 0, fat_g: 10, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-taco-salad',
    title: 'Chicken taco salad',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken', 'taco'],
    ingredients: ['Chicken breast', 'Salad', 'Salsa', 'Greek yogurt'],
    notes: 'No chips and no tortilla. Yogurt instead of sour cream.',
    logItems: [
      { name: 'Chicken breast (5 oz)', calories: 230, protein_g: 44, carbs_g: 0, fat_g: 5, fiber_g: 0 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-turkey-chili',
    title: 'Turkey chili bowl',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'turkey', 'chili'],
    ingredients: ['Ground turkey', 'Beans', 'Tomatoes'],
    notes: 'One bowl. Skip the cheese pile.',
    logItems: [
      { name: 'Turkey chili (bowl)', calories: 340, protein_g: 32, carbs_g: 28, fat_g: 8, fiber_g: 10 },
    ],
  },
  {
    id: 'lean-cottage-berries',
    title: 'Cottage cheese and berries',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy'],
    ingredients: ['Cottage cheese', 'Berries', 'Egg whites'],
    notes: 'Low-fat cottage cheese. Egg whites if you want more protein.',
    logItems: [
      { name: 'Cottage cheese (1 cup)', calories: 180, protein_g: 24, carbs_g: 8, fat_g: 5, fiber_g: 0 },
      { name: 'Egg whites (3)', calories: 50, protein_g: 11, carbs_g: 1, fat_g: 0, fiber_g: 0 },
      { name: 'Berries (1 cup)', calories: 70, protein_g: 1, carbs_g: 17, fat_g: 0, fiber_g: 8 },
    ],
  },
  {
    id: 'lean-salmon-eggs',
    title: 'Smoked salmon and eggs',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'fish', 'egg'],
    ingredients: ['Smoked salmon', 'Eggs', 'Greek yogurt'],
    notes: 'A few slices of salmon. Yogurt on the side.',
    logItems: [
      { name: 'Smoked salmon (3 oz)', calories: 100, protein_g: 16, carbs_g: 0, fat_g: 4, fiber_g: 0 },
      { name: 'Eggs (2 large)', calories: 140, protein_g: 12, carbs_g: 1, fat_g: 10, fiber_g: 0 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-turkey-sausage-eggs',
    title: 'Turkey sausage and eggs',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'turkey', 'egg'],
    ingredients: ['Turkey sausage', 'Eggs', 'Spinach'],
    notes: 'Two links. Spinach in the pan.',
    logItems: [
      { name: 'Turkey sausage (2 links)', calories: 140, protein_g: 14, carbs_g: 2, fat_g: 8, fiber_g: 0 },
      { name: 'Eggs (2 large)', calories: 140, protein_g: 12, carbs_g: 1, fat_g: 10, fiber_g: 0 },
      { name: 'Cheese stick', calories: 80, protein_g: 7, carbs_g: 1, fat_g: 6, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-protein-oats',
    title: 'Protein oats',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy'],
    ingredients: ['Oats', 'Protein shake', 'Berries'],
    notes: 'Stir the shake into hot oats. Berries on top.',
    logItems: [
      { name: 'Oatmeal (1 cup cooked)', calories: 160, protein_g: 6, carbs_g: 28, fat_g: 3, fiber_g: 4 },
      { name: 'Protein shake', calories: 150, protein_g: 25, carbs_g: 6, fat_g: 2, fiber_g: 1 },
      { name: 'Berries (½ cup)', calories: 35, protein_g: 0, carbs_g: 8, fat_g: 0, fiber_g: 4 },
    ],
  },
  {
    id: 'lean-egg-white-omelet',
    title: 'Chicken egg-white omelet',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken', 'egg'],
    ingredients: ['Egg whites', 'Chicken breast', 'Spinach'],
    notes: 'Four whites. Leftover chicken in the middle.',
    logItems: [
      { name: 'Egg whites (4)', calories: 70, protein_g: 14, carbs_g: 1, fat_g: 0, fiber_g: 0 },
      { name: 'Chicken breast (4 oz)', calories: 185, protein_g: 35, carbs_g: 0, fat_g: 4, fiber_g: 0 },
      { name: 'Spinach (2 cups)', calories: 15, protein_g: 2, carbs_g: 2, fat_g: 0, fiber_g: 1 },
    ],
  },
  {
    id: 'lean-canadian-bacon',
    title: 'Canadian bacon and eggs',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'egg'],
    ingredients: ['Canadian bacon', 'Eggs', 'Greek yogurt'],
    notes: 'Three slices. Yogurt on the side.',
    logItems: [
      { name: 'Canadian bacon (3 slices)', calories: 90, protein_g: 15, carbs_g: 1, fat_g: 3, fiber_g: 0 },
      { name: 'Eggs (2 large)', calories: 140, protein_g: 12, carbs_g: 1, fat_g: 10, fiber_g: 0 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-tofu-scramble',
    title: 'Tofu scramble',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'veg'],
    ingredients: ['Firm tofu', 'Eggs', 'Peppers'],
    notes: 'Crumble the tofu into the eggs.',
    logItems: [
      { name: 'Firm tofu (6 oz)', calories: 180, protein_g: 20, carbs_g: 6, fat_g: 9, fiber_g: 2 },
      { name: 'Eggs (2 large)', calories: 140, protein_g: 12, carbs_g: 1, fat_g: 10, fiber_g: 0 },
      { name: 'Bell peppers', calories: 30, protein_g: 1, carbs_g: 6, fat_g: 0, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-chicken-breakfast',
    title: 'Leftover chicken breakfast',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Egg', 'Salsa'],
    notes: 'Warm the chicken. One egg and salsa.',
    logItems: [
      { name: 'Chicken breast (5 oz)', calories: 230, protein_g: 44, carbs_g: 0, fat_g: 5, fiber_g: 0 },
      { name: 'Egg (1 large)', calories: 70, protein_g: 6, carbs_g: 0, fat_g: 5, fiber_g: 0 },
      { name: 'Salsa', calories: 20, protein_g: 1, carbs_g: 4, fat_g: 0, fiber_g: 1 },
    ],
  },
  {
    id: 'lean-cottage-toast',
    title: 'Cottage cheese toast',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy'],
    ingredients: ['Cottage cheese', 'Toast', 'Egg white'],
    notes: 'One slice of toast. Cottage cheese on top.',
    logItems: [
      { name: 'Cottage cheese (1 cup)', calories: 180, protein_g: 24, carbs_g: 8, fat_g: 5, fiber_g: 0 },
      { name: 'Toast (1 slice)', calories: 80, protein_g: 4, carbs_g: 14, fat_g: 1, fiber_g: 2 },
      { name: 'Egg whites (2)', calories: 35, protein_g: 7, carbs_g: 0, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-shrimp-eggs',
    title: 'Shrimp and eggs',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'shrimp', 'egg'],
    ingredients: ['Shrimp', 'Eggs', 'Spinach'],
    notes: 'Sear the shrimp, then scramble the eggs in the same pan.',
    logItems: [
      { name: 'Shrimp (4 oz)', calories: 120, protein_g: 23, carbs_g: 1, fat_g: 2, fiber_g: 0 },
      { name: 'Eggs (2 large)', calories: 140, protein_g: 12, carbs_g: 1, fat_g: 10, fiber_g: 0 },
      { name: 'Spinach (2 cups)', calories: 15, protein_g: 2, carbs_g: 2, fat_g: 0, fiber_g: 1 },
    ],
  },
  {
    id: 'lean-ham-whites',
    title: 'Ham and egg whites',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'egg'],
    ingredients: ['Ham', 'Egg whites', 'Broccoli'],
    notes: 'Lean ham. Four whites. Broccoli on the side.',
    logItems: [
      { name: 'Ham (3 oz)', calories: 90, protein_g: 14, carbs_g: 2, fat_g: 3, fiber_g: 0 },
      { name: 'Egg whites (4)', calories: 70, protein_g: 14, carbs_g: 1, fat_g: 0, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
    ],
  },
  {
    id: 'lean-chicken-cucumber',
    title: 'Chicken and cucumber',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Cucumber', 'Salt'],
    notes: 'Cold chicken. Sliced cucumber. Salt and pepper.',
    logItems: [
      { name: 'Chicken breast (6 oz)', calories: 280, protein_g: 52, carbs_g: 0, fat_g: 6, fiber_g: 0 },
      { name: 'Cucumber', calories: 16, protein_g: 1, carbs_g: 4, fat_g: 0, fiber_g: 1 },
    ],
  },
  {
    id: 'lean-tuna-yogurt',
    title: 'Tuna with yogurt',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Tuna in water', 'Greek yogurt', 'Cucumber'],
    notes: 'No mayo. Yogurt, salt, and cucumber.',
    logItems: [
      { name: 'Tuna in water (5 oz)', calories: 150, protein_g: 33, carbs_g: 0, fat_g: 1, fiber_g: 0 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
      { name: 'Cucumber', calories: 16, protein_g: 1, carbs_g: 4, fat_g: 0, fiber_g: 1 },
    ],
  },
  {
    id: 'lean-shrimp-cocktail',
    title: 'Shrimp cocktail plate',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'shrimp'],
    ingredients: ['Shrimp', 'Cocktail sauce', 'Salad'],
    notes: 'A small spoon of cocktail sauce. Greens on the side.',
    logItems: [
      { name: 'Shrimp (8 oz)', calories: 240, protein_g: 46, carbs_g: 2, fat_g: 4, fiber_g: 0 },
      { name: 'Side salad', calories: 40, protein_g: 1, carbs_g: 6, fat_g: 1, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-turkey-apple',
    title: 'Turkey and apple',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'turkey'],
    ingredients: ['Turkey slices', 'Apple', 'Cheese'],
    notes: 'Half a cheese stick. Apple on the side.',
    logItems: [
      { name: 'Turkey slices (5 oz)', calories: 175, protein_g: 30, carbs_g: 2, fat_g: 4, fiber_g: 0 },
      { name: 'Apple', calories: 95, protein_g: 0, carbs_g: 25, fat_g: 0, fiber_g: 4 },
      { name: 'Cheese (½ stick)', calories: 40, protein_g: 4, carbs_g: 0, fat_g: 3, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-lettuce-wraps',
    title: 'Chicken lettuce wraps',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Lettuce', 'Greek yogurt'],
    notes: 'Spoon chicken into lettuce. Yogurt instead of a heavy sauce.',
    logItems: [
      { name: 'Chicken breast (5 oz)', calories: 230, protein_g: 44, carbs_g: 0, fat_g: 5, fiber_g: 0 },
      { name: 'Lettuce leaves', calories: 10, protein_g: 1, carbs_g: 2, fat_g: 0, fiber_g: 1 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-egg-salad',
    title: 'Light egg salad',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'egg'],
    ingredients: ['Eggs', 'Greek yogurt', 'Salad'],
    notes: 'Yogurt instead of mayo. Salad instead of bread.',
    logItems: [
      { name: 'Eggs (3 large)', calories: 210, protein_g: 18, carbs_g: 2, fat_g: 15, fiber_g: 0 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-salmon-salad',
    title: 'Salmon salad',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Salmon', 'Salad', 'Greek yogurt'],
    notes: 'Flake cooked salmon over greens.',
    logItems: [
      { name: 'Salmon (4 oz)', calories: 230, protein_g: 25, carbs_g: 0, fat_g: 14, fiber_g: 0 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-chicken-salsa',
    title: 'Chicken and salsa',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Salsa', 'Peppers'],
    notes: 'Warm chicken. Salsa on top. No tortilla.',
    logItems: [
      { name: 'Chicken breast (6 oz)', calories: 280, protein_g: 52, carbs_g: 0, fat_g: 6, fiber_g: 0 },
      { name: 'Salsa', calories: 20, protein_g: 1, carbs_g: 4, fat_g: 0, fiber_g: 1 },
      { name: 'Bell peppers', calories: 30, protein_g: 1, carbs_g: 6, fat_g: 0, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-tuna-beans',
    title: 'Tuna and white beans',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Tuna in water', 'White beans', 'Salad'],
    notes: 'Half a cup of beans. Rinse them.',
    logItems: [
      { name: 'Tuna in water (4 oz)', calories: 120, protein_g: 26, carbs_g: 0, fat_g: 1, fiber_g: 0 },
      { name: 'White beans (½ cup)', calories: 110, protein_g: 7, carbs_g: 20, fat_g: 0, fiber_g: 6 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-shrimp-zucchini',
    title: 'Shrimp and zucchini',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'shrimp'],
    ingredients: ['Shrimp', 'Zucchini', 'Garlic'],
    notes: 'Sear both in one pan. Garlic and salt.',
    logItems: [
      { name: 'Shrimp (8 oz)', calories: 240, protein_g: 46, carbs_g: 2, fat_g: 4, fiber_g: 0 },
      { name: 'Zucchini', calories: 30, protein_g: 2, carbs_g: 6, fat_g: 0, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-cod-lettuce',
    title: 'Cod lettuce tacos',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'fish', 'taco'],
    ingredients: ['Cod', 'Lettuce', 'Salsa', 'Greek yogurt'],
    notes: 'Lettuce instead of a tortilla.',
    logItems: [
      { name: 'Cod (5 oz)', calories: 150, protein_g: 32, carbs_g: 0, fat_g: 1, fiber_g: 0 },
      { name: 'Salsa', calories: 20, protein_g: 1, carbs_g: 4, fat_g: 0, fiber_g: 1 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-chicken-tomato',
    title: 'Chicken and tomatoes',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Tomatoes', 'Mozzarella'],
    notes: 'A small piece of mozzarella. Skip the bread.',
    logItems: [
      { name: 'Chicken breast (5 oz)', calories: 230, protein_g: 44, carbs_g: 0, fat_g: 5, fiber_g: 0 },
      { name: 'Tomatoes', calories: 30, protein_g: 1, carbs_g: 6, fat_g: 0, fiber_g: 2 },
      { name: 'Mozzarella (1 oz)', calories: 80, protein_g: 6, carbs_g: 1, fat_g: 6, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-chicken-edamame',
    title: 'Chicken and edamame',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Edamame'],
    notes: 'Cold or warm. Salt the edamame.',
    logItems: [
      { name: 'Chicken breast (4 oz)', calories: 185, protein_g: 35, carbs_g: 0, fat_g: 4, fiber_g: 0 },
      { name: 'Edamame (1 cup)', calories: 190, protein_g: 17, carbs_g: 14, fat_g: 8, fiber_g: 8 },
    ],
  },
  {
    id: 'lean-tuna-edamame',
    title: 'Tuna and edamame',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Tuna in water', 'Edamame'],
    notes: 'Mix and salt. No mayo.',
    logItems: [
      { name: 'Tuna in water (4 oz)', calories: 120, protein_g: 26, carbs_g: 0, fat_g: 1, fiber_g: 0 },
      { name: 'Edamame (1 cup)', calories: 190, protein_g: 17, carbs_g: 14, fat_g: 8, fiber_g: 8 },
    ],
  },
  {
    id: 'lean-ham-cottage',
    title: 'Ham and cottage cheese',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy'],
    ingredients: ['Ham', 'Cottage cheese'],
    notes: 'Lean ham. Low-fat cottage cheese.',
    logItems: [
      { name: 'Ham (3 oz)', calories: 120, protein_g: 18, carbs_g: 2, fat_g: 4, fiber_g: 0 },
      { name: 'Cottage cheese (1 cup)', calories: 180, protein_g: 24, carbs_g: 8, fat_g: 5, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-chicken-cottage',
    title: 'Chicken and cottage cheese',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Cottage cheese'],
    notes: 'Cold chicken. Cottage cheese on the side.',
    logItems: [
      { name: 'Chicken breast (4 oz)', calories: 185, protein_g: 35, carbs_g: 0, fat_g: 4, fiber_g: 0 },
      { name: 'Cottage cheese (¾ cup)', calories: 135, protein_g: 18, carbs_g: 6, fat_g: 4, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-fajita-plate',
    title: 'Chicken fajita plate',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Peppers', 'Onion'],
    notes: 'No tortilla. Peppers and onion in the same pan.',
    logItems: [
      { name: 'Chicken breast (5 oz)', calories: 230, protein_g: 44, carbs_g: 0, fat_g: 5, fiber_g: 0 },
      { name: 'Bell peppers', calories: 40, protein_g: 1, carbs_g: 8, fat_g: 0, fiber_g: 2 },
      { name: 'Onion', calories: 20, protein_g: 0, carbs_g: 5, fat_g: 0, fiber_g: 1 },
    ],
  },
  {
    id: 'lean-sirloin',
    title: 'Sirloin and broccoli',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'beef'],
    ingredients: ['Sirloin', 'Broccoli', 'Greek yogurt'],
    notes: 'Trim the fat. Yogurt and horseradish if you want a sauce.',
    logItems: [
      { name: 'Sirloin (4 oz)', calories: 200, protein_g: 26, carbs_g: 0, fat_g: 10, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-pork-tenderloin',
    title: 'Pork tenderloin and greens',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'pork'],
    ingredients: ['Pork tenderloin', 'Broccoli', 'Salad'],
    notes: 'The tenderloin, not a chop with a fat cap.',
    logItems: [
      { name: 'Pork tenderloin (5 oz)', calories: 175, protein_g: 32, carbs_g: 0, fat_g: 5, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
      { name: 'Side salad', calories: 40, protein_g: 1, carbs_g: 6, fat_g: 1, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-turkey-burger',
    title: 'Turkey burger, no bun',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'turkey'],
    ingredients: ['Ground turkey', 'Salad', 'Cheese'],
    notes: 'Skip the bun. One thin slice of cheese.',
    logItems: [
      { name: 'Ground turkey (4 oz)', calories: 170, protein_g: 22, carbs_g: 0, fat_g: 9, fiber_g: 0 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
      { name: 'Cheese slice', calories: 80, protein_g: 5, carbs_g: 1, fat_g: 6, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-shrimp-stir',
    title: 'Shrimp and peppers',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['lean', 'easy', 'shrimp'],
    ingredients: ['Shrimp', 'Broccoli', 'Peppers'],
    notes: 'No rice. A splash of soy if you want.',
    logItems: [
      { name: 'Shrimp (6 oz)', calories: 180, protein_g: 35, carbs_g: 2, fat_g: 3, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
      { name: 'Bell peppers', calories: 40, protein_g: 1, carbs_g: 8, fat_g: 0, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-chicken-soup',
    title: 'Chicken vegetable soup',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['lean', 'easy', 'chicken', 'soup'],
    ingredients: ['Chicken breast', 'Broth', 'Vegetables'],
    notes: 'One bowl. Chicken in the broth, not noodles.',
    logItems: [
      { name: 'Chicken breast (4 oz)', calories: 185, protein_g: 35, carbs_g: 0, fat_g: 4, fiber_g: 0 },
      { name: 'Vegetable broth and veg', calories: 60, protein_g: 3, carbs_g: 10, fat_g: 1, fiber_g: 3 },
    ],
  },
  {
    id: 'lean-tilapia',
    title: 'Tilapia and asparagus',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Tilapia', 'Asparagus', 'Lemon'],
    notes: 'Bake both. Lemon and salt.',
    logItems: [
      { name: 'Tilapia (6 oz)', calories: 220, protein_g: 42, carbs_g: 0, fat_g: 4, fiber_g: 0 },
      { name: 'Asparagus (1 cup)', calories: 40, protein_g: 4, carbs_g: 6, fat_g: 0, fiber_g: 3 },
    ],
  },
  {
    id: 'lean-chicken-zucchini',
    title: 'Chicken and zucchini',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Zucchini'],
    notes: 'Slice the zucchini thin so it cooks with the chicken.',
    logItems: [
      { name: 'Chicken breast (6 oz)', calories: 280, protein_g: 52, carbs_g: 0, fat_g: 6, fiber_g: 0 },
      { name: 'Zucchini', calories: 40, protein_g: 2, carbs_g: 7, fat_g: 0, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-beef-peppers',
    title: 'Beef and peppers',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'beef'],
    ingredients: ['Lean ground beef', 'Peppers', 'Greek yogurt'],
    notes: 'Drain the beef. Yogurt on the side.',
    logItems: [
      { name: 'Lean ground beef (4 oz)', calories: 220, protein_g: 22, carbs_g: 0, fat_g: 14, fiber_g: 0 },
      { name: 'Bell peppers', calories: 40, protein_g: 1, carbs_g: 8, fat_g: 0, fiber_g: 2 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-salmon-asparagus',
    title: 'Salmon and asparagus',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Salmon', 'Asparagus', 'Greek yogurt'],
    notes: 'Bake the salmon. Yogurt and lemon.',
    logItems: [
      { name: 'Salmon (4 oz)', calories: 230, protein_g: 25, carbs_g: 0, fat_g: 14, fiber_g: 0 },
      { name: 'Asparagus (1 cup)', calories: 40, protein_g: 4, carbs_g: 6, fat_g: 0, fiber_g: 3 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-chicken-meatballs',
    title: 'Chicken meatballs and salad',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Ground chicken', 'Salad'],
    notes: 'Bake the meatballs. Salad instead of pasta.',
    logItems: [
      { name: 'Chicken meatballs (4 oz)', calories: 180, protein_g: 28, carbs_g: 4, fat_g: 6, fiber_g: 0 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-tuna-steak',
    title: 'Tuna steak and broccoli',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Tuna steak', 'Broccoli'],
    notes: 'Sear the tuna. Salt and lemon.',
    logItems: [
      { name: 'Tuna steak (5 oz)', calories: 180, protein_g: 40, carbs_g: 0, fat_g: 2, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
    ],
  },
  {
    id: 'lean-chicken-mushrooms',
    title: 'Chicken and mushrooms',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Mushrooms', 'Spinach'],
    notes: 'One pan. A splash of broth if it sticks.',
    logItems: [
      { name: 'Chicken breast (5 oz)', calories: 230, protein_g: 44, carbs_g: 0, fat_g: 5, fiber_g: 0 },
      { name: 'Mushrooms', calories: 20, protein_g: 2, carbs_g: 3, fat_g: 0, fiber_g: 1 },
      { name: 'Spinach (2 cups)', calories: 15, protein_g: 2, carbs_g: 2, fat_g: 0, fiber_g: 1 },
    ],
  },
  {
    id: 'lean-turkey-beans',
    title: 'Turkey and green beans',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'turkey'],
    ingredients: ['Turkey breast', 'Green beans'],
    notes: 'Roast or pan-cook the turkey. Steam the beans.',
    logItems: [
      { name: 'Turkey breast (5 oz)', calories: 200, protein_g: 35, carbs_g: 0, fat_g: 4, fiber_g: 0 },
      { name: 'Green beans (1 cup)', calories: 40, protein_g: 2, carbs_g: 8, fat_g: 0, fiber_g: 4 },
    ],
  },
  {
    id: 'lean-scallops',
    title: 'Scallops and salad',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Scallops', 'Salad'],
    notes: 'Sear the scallops in a dry pan. Salad on the side.',
    logItems: [
      { name: 'Scallops (6 oz)', calories: 180, protein_g: 36, carbs_g: 6, fat_g: 2, fiber_g: 0 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-chicken-cabbage',
    title: 'Chicken and cabbage',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Cabbage'],
    notes: 'Shred the cabbage into the pan at the end.',
    logItems: [
      { name: 'Chicken breast (5 oz)', calories: 230, protein_g: 44, carbs_g: 0, fat_g: 5, fiber_g: 0 },
      { name: 'Cabbage (2 cups)', calories: 40, protein_g: 2, carbs_g: 8, fat_g: 0, fiber_g: 3 },
    ],
  },
  {
    id: 'lean-chicken-beans',
    title: 'Chicken and black beans',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Black beans', 'Salsa'],
    notes: 'Half a cup of beans. Salsa on top.',
    logItems: [
      { name: 'Chicken breast (4 oz)', calories: 185, protein_g: 35, carbs_g: 0, fat_g: 4, fiber_g: 0 },
      { name: 'Black beans (½ cup)', calories: 110, protein_g: 7, carbs_g: 20, fat_g: 0, fiber_g: 7 },
      { name: 'Salsa', calories: 20, protein_g: 1, carbs_g: 4, fat_g: 0, fiber_g: 1 },
    ],
  },
  {
    id: 'lean-chicken-eggs-dinner',
    title: 'Chicken and eggs',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken', 'egg'],
    ingredients: ['Chicken breast', 'Eggs', 'Spinach'],
    notes: 'Warm the chicken. Fry the eggs. Spinach underneath.',
    logItems: [
      { name: 'Chicken breast (4 oz)', calories: 185, protein_g: 35, carbs_g: 0, fat_g: 4, fiber_g: 0 },
      { name: 'Eggs (2 large)', calories: 140, protein_g: 12, carbs_g: 1, fat_g: 10, fiber_g: 0 },
      { name: 'Spinach (2 cups)', calories: 15, protein_g: 2, carbs_g: 2, fat_g: 0, fiber_g: 1 },
    ],
  },
  {
    id: 'lean-shrimp-tomato',
    title: 'Shrimp and tomatoes',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['lean', 'easy', 'shrimp'],
    ingredients: ['Shrimp', 'Tomatoes', 'Garlic'],
    notes: 'Sear the shrimp. Tomatoes in the pan for a minute.',
    logItems: [
      { name: 'Shrimp (8 oz)', calories: 240, protein_g: 46, carbs_g: 2, fat_g: 4, fiber_g: 0 },
      { name: 'Tomatoes', calories: 40, protein_g: 2, carbs_g: 8, fat_g: 0, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-pork-apple',
    title: 'Pork tenderloin and apple',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'pork'],
    ingredients: ['Pork tenderloin', 'Apple', 'Broccoli'],
    notes: 'Plain apple, not a sweet glaze. Broccoli on the side.',
    logItems: [
      { name: 'Pork tenderloin (5 oz)', calories: 175, protein_g: 32, carbs_g: 0, fat_g: 5, fiber_g: 0 },
      { name: 'Apple', calories: 95, protein_g: 0, carbs_g: 25, fat_g: 0, fiber_g: 4 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
    ],
  },
  {
    id: 'lean-egg-whites-turkey',
    title: 'Turkey and egg whites',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'turkey', 'egg'],
    ingredients: ['Turkey slices', 'Egg whites', 'Spinach'],
    notes: 'Warm the turkey. Scramble the whites with spinach.',
    logItems: [
      { name: 'Turkey slices (4 oz)', calories: 140, protein_g: 24, carbs_g: 2, fat_g: 3, fiber_g: 0 },
      { name: 'Egg whites (4)', calories: 70, protein_g: 14, carbs_g: 1, fat_g: 0, fiber_g: 0 },
      { name: 'Spinach (2 cups)', calories: 15, protein_g: 2, carbs_g: 2, fat_g: 0, fiber_g: 1 },
    ],
  },
  {
    id: 'lean-seared-chicken',
    title: 'Seared chicken and spinach',
    meal: 'dinner',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Spinach', 'Greek yogurt'],
    notes: 'Sear the chicken. Wilt the spinach. Yogurt on the side.',
    logItems: [
      { name: 'Chicken breast (5 oz)', calories: 230, protein_g: 44, carbs_g: 0, fat_g: 5, fiber_g: 0 },
      { name: 'Spinach (2 cups)', calories: 15, protein_g: 2, carbs_g: 2, fat_g: 0, fiber_g: 1 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-tuna-greens',
    title: 'Tuna and greens',
    meal: 'lunch',
    meals: ['lunch', 'dinner'],
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Tuna in water', 'Spinach', 'Broccoli'],
    notes: 'Drain the tuna. Warm the greens. No mayo.',
    logItems: [
      { name: 'Tuna in water (5 oz)', calories: 150, protein_g: 33, carbs_g: 0, fat_g: 1, fiber_g: 0 },
      { name: 'Spinach (2 cups)', calories: 15, protein_g: 2, carbs_g: 2, fat_g: 0, fiber_g: 1 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
    ],
  },
];
