/** One plate each. Built for a cut: under 450 kcal, about 30g protein or more. */
export const LEAN_RECIPES = [
  {
    id: 'lean-yogurt-eggs',
    title: 'Yogurt, eggs, and berries',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'yogurt', 'egg'],
    ingredients: ['Greek yogurt', 'Eggs', 'Berries'],
    notes: 'Plain yogurt. Berries on the side.',
    logItems: [
      { name: 'Greek yogurt (1 cup)', calories: 130, protein_g: 22, carbs_g: 8, fat_g: 0, fiber_g: 0 },
      { name: 'Eggs (2 large)', calories: 140, protein_g: 12, carbs_g: 1, fat_g: 10, fiber_g: 0 },
      { name: 'Berries (1 cup)', calories: 70, protein_g: 1, carbs_g: 17, fat_g: 0, fiber_g: 8 },
    ],
  },
  {
    id: 'lean-chicken-scramble',
    title: 'Chicken and egg scramble',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken', 'egg'],
    ingredients: ['Chicken breast', 'Eggs', 'Broccoli'],
    notes: 'Chop leftover chicken into the eggs. Broccoli on the side.',
    logItems: [
      { name: 'Chicken breast (4 oz)', calories: 185, protein_g: 35, carbs_g: 0, fat_g: 4, fiber_g: 0 },
      { name: 'Eggs (2 large)', calories: 140, protein_g: 12, carbs_g: 1, fat_g: 10, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
    ],
  },
  {
    id: 'lean-shake-yogurt',
    title: 'Shake and yogurt',
    meal: 'breakfast',
    kidOk: true,
    tags: ['lean', 'easy', 'yogurt'],
    ingredients: ['Protein shake', 'Greek yogurt'],
    notes: 'Drink the shake. Eat the yogurt. No granola.',
    logItems: [
      { name: 'Protein shake', calories: 150, protein_g: 25, carbs_g: 6, fat_g: 2, fiber_g: 1 },
      { name: 'Greek yogurt (1 cup)', calories: 130, protein_g: 22, carbs_g: 8, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-chicken-salad',
    title: 'Chicken salad plate',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Salad', 'Vinaigrette'],
    notes: 'No bread. Use a light vinaigrette.',
    logItems: [
      { name: 'Chicken breast (4 oz)', calories: 185, protein_g: 35, carbs_g: 0, fat_g: 4, fiber_g: 0 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-tuna-plate',
    title: 'Tuna and salad',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Tuna in water', 'Salad', 'Greek yogurt'],
    notes: 'Stir the tuna with yogurt instead of mayo.',
    logItems: [
      { name: 'Tuna in water (4 oz)', calories: 120, protein_g: 26, carbs_g: 0, fat_g: 1, fiber_g: 0 },
      { name: 'Greek yogurt (1 cup)', calories: 130, protein_g: 22, carbs_g: 8, fat_g: 0, fiber_g: 0 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-shrimp-broccoli',
    title: 'Shrimp and broccoli',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'shrimp'],
    ingredients: ['Shrimp', 'Broccoli', 'Lemon'],
    notes: 'Sear the shrimp. Steam the broccoli. Lemon and salt.',
    logItems: [
      { name: 'Shrimp (8 oz)', calories: 240, protein_g: 46, carbs_g: 2, fat_g: 4, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
    ],
  },
  {
    id: 'lean-turkey-rolls',
    title: 'Turkey roll-ups',
    meal: 'lunch',
    kidOk: true,
    tags: ['lean', 'easy', 'turkey'],
    ingredients: ['Turkey slices', 'Cheese', 'Salad'],
    notes: 'Roll turkey around a cheese stick. Salad on the side.',
    logItems: [
      { name: 'Turkey slices (4 oz)', calories: 140, protein_g: 24, carbs_g: 2, fat_g: 3, fiber_g: 0 },
      { name: 'Cheese stick', calories: 80, protein_g: 7, carbs_g: 1, fat_g: 6, fiber_g: 0 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-chicken-broccoli',
    title: 'Chicken and broccoli',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Chicken breast', 'Broccoli'],
    notes: 'Bake or pan-cook the chicken. No rice.',
    logItems: [
      { name: 'Chicken breast (6 oz)', calories: 280, protein_g: 52, carbs_g: 0, fat_g: 6, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
    ],
  },
  {
    id: 'lean-salmon-plate',
    title: 'Salmon and broccoli',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Salmon', 'Broccoli', 'Greek yogurt'],
    notes: 'Bake the salmon. Yogurt and lemon on the side.',
    logItems: [
      { name: 'Salmon (4 oz)', calories: 230, protein_g: 25, carbs_g: 0, fat_g: 14, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-beef-greens',
    title: 'Lean beef and greens',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'beef'],
    ingredients: ['Lean ground beef', 'Broccoli', 'Greek yogurt'],
    notes: 'Brown the beef with salt and pepper. Skip the bun.',
    logItems: [
      { name: 'Lean ground beef (4 oz)', calories: 220, protein_g: 22, carbs_g: 0, fat_g: 14, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-cod-plate',
    title: 'Cod and greens',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'fish'],
    ingredients: ['Cod', 'Salad', 'Broccoli'],
    notes: 'Bake the cod with lemon. Greens on the side.',
    logItems: [
      { name: 'Cod (6 oz)', calories: 180, protein_g: 39, carbs_g: 0, fat_g: 2, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-rotisserie',
    title: 'Rotisserie chicken plate',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken'],
    ingredients: ['Rotisserie chicken', 'Broccoli', 'Salad'],
    notes: 'Take the breast. Skip the skin and the potatoes.',
    logItems: [
      { name: 'Rotisserie chicken (5 oz)', calories: 240, protein_g: 35, carbs_g: 0, fat_g: 10, fiber_g: 0 },
      { name: 'Broccoli (1 cup)', calories: 55, protein_g: 4, carbs_g: 11, fat_g: 0, fiber_g: 5 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
    ],
  },
  {
    id: 'lean-taco-salad',
    title: 'Chicken taco salad',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'chicken', 'taco'],
    ingredients: ['Chicken breast', 'Salad', 'Salsa', 'Greek yogurt'],
    notes: 'No chips and no tortilla. Yogurt instead of sour cream.',
    logItems: [
      { name: 'Chicken breast (5 oz)', calories: 230, protein_g: 44, carbs_g: 0, fat_g: 5, fiber_g: 0 },
      { name: 'Mixed salad + vinaigrette', calories: 150, protein_g: 3, carbs_g: 8, fat_g: 12, fiber_g: 2 },
      { name: 'Greek yogurt (½ cup)', calories: 65, protein_g: 11, carbs_g: 4, fat_g: 0, fiber_g: 0 },
    ],
  },
  {
    id: 'lean-turkey-chili',
    title: 'Turkey chili bowl',
    meal: 'dinner',
    kidOk: true,
    tags: ['lean', 'easy', 'turkey', 'chili'],
    ingredients: ['Ground turkey', 'Beans', 'Tomatoes'],
    notes: 'One bowl. Skip the cheese pile.',
    logItems: [
      { name: 'Turkey chili (bowl)', calories: 340, protein_g: 32, carbs_g: 28, fat_g: 8, fiber_g: 10 },
    ],
  },
];
