@echo off
echo Starting Kaeluma Development Server...
start cmd /k "npm run dev"
echo Waiting for server to start...
timeout /t 2 /nobreak >nul
echo Opening app in your browser...
start http://localhost:3000/
